In [2]:
import torch
import numpy as np

c:\Users\Sam\miniconda3\envs\wisp\lib\site-packages\tqdm-4.64.1-py3.9.egg\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
M=np.array([
        [
          0.9949493563944524,
          -0.020502346593855254,
          0.0982620576863761,
          0.49400064930106524
        ],
        [
          0.09425991666129768,
          -0.1457059879252915,
          -0.9848273113564319,
          -3.999885410086487
        ],
        [
          0.034508641063289575,
          0.9891154729622466,
          -0.1430375294277888,
          -0.47155737598383146
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ])

In [4]:
M

array([[ 0.99494936, -0.02050235,  0.09826206,  0.49400065],
       [ 0.09425992, -0.14570599, -0.98482731, -3.99988541],
       [ 0.03450864,  0.98911547, -0.14303753, -0.47155738],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
np.linalg.inv(M)

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [23]:
A=np.zeros_like(M)
A[:3,:3]=M[:3,:3].T
A[:3,-1]=np.matmul(-M[:3,:3].T, M[:3, -1])
A[3,3]=1
A

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [24]:
np.abs(np.linalg.inv(M)-A)<1e-8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [3]:
class test():
    def __init__(self,a):
        return a+1

In [4]:
test(1)

TypeError: __init__() should return None, not 'int'