In [1]:
import torch
import numpy as np

c:\Users\Sam\miniconda3\envs\wisp1\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
M=np.array([
        [
          0.9949493563944524,
          -0.020502346593855254,
          0.0982620576863761,
          0.49400064930106524
        ],
        [
          0.09425991666129768,
          -0.1457059879252915,
          -0.9848273113564319,
          -3.999885410086487
        ],
        [
          0.034508641063289575,
          0.9891154729622466,
          -0.1430375294277888,
          -0.47155737598383146
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ])

In [3]:
M

array([[ 0.99494936, -0.02050235,  0.09826206,  0.49400065],
       [ 0.09425992, -0.14570599, -0.98482731, -3.99988541],
       [ 0.03450864,  0.98911547, -0.14303753, -0.47155738],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
np.linalg.inv(M)

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [23]:
A=np.zeros_like(M)
A[:3,:3]=M[:3,:3].T
A[:3,-1]=np.matmul(-M[:3,:3].T, M[:3, -1])
A[3,3]=1
A

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [24]:
np.abs(np.linalg.inv(M)-A)<1e-8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [8]:
import torch
M=torch.randn(3,4,4)
M

tensor([[[-0.3516,  1.1145,  0.2488,  0.8461],
         [ 1.0391,  1.0456,  0.9945, -0.0475],
         [ 0.7627, -0.0817, -0.6598, -1.8965],
         [ 0.9918, -1.1941, -0.6342, -0.6497]],

        [[ 0.9352, -0.1054, -0.9436, -0.5705],
         [-0.3920, -0.3373, -0.4434,  0.1394],
         [ 0.7392, -0.7222,  0.7845, -0.5661],
         [-0.3790,  0.9515,  0.1758, -0.2998]],

        [[ 0.3109, -1.8951,  1.7036,  1.1228],
         [-1.2023,  0.1315, -0.9544, -0.7449],
         [ 0.1932, -2.0160, -0.1076, -0.3073],
         [-1.1677, -0.9357, -0.6709, -0.7698]]])

In [14]:
import numpy as np
idx0=torch.tensor([[0,1]])
idx1=torch.tensor([[1,1]])
M[idx0,idx1]

tensor([[[ 1.0391,  1.0456,  0.9945, -0.0475],
         [-0.3920, -0.3373, -0.4434,  0.1394]]])

In [4]:
M[[0,0,0,0,0,1,2,1,2,1]].shape

torch.Size([10, 4, 4])

In [5]:
M[torch.Tensor([0,1,4,5,6,7]).long(),:3,-1].shape

IndexError: index 4 is out of bounds for dimension 0 with size 3

In [ ]:
(torch.randn(10,4,5)@torch.randn(10,5,2)).shape

torch.Size([10, 4, 2])

In [ ]:
import torch

idx=torch.arange(10)
idx

c:\Users\Sam\miniconda3\envs\wisp1\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
perm=torch.randperm(10)
perm

tensor([7, 8, 5, 3, 4, 6, 9, 2, 1, 0])

In [ ]:
idx.reshape(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])