In [1]:
import torch
import numpy as np

c:\Users\Sam\miniconda3\envs\wisp1\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
M=np.array([
        [
          0.9949493563944524,
          -0.020502346593855254,
          0.0982620576863761,
          0.49400064930106524
        ],
        [
          0.09425991666129768,
          -0.1457059879252915,
          -0.9848273113564319,
          -3.999885410086487
        ],
        [
          0.034508641063289575,
          0.9891154729622466,
          -0.1430375294277888,
          -0.47155737598383146
        ],
        [
          0.0,
          0.0,
          0.0,
          1.0
        ]
      ])

In [3]:
M

array([[ 0.99494936, -0.02050235,  0.09826206,  0.49400065],
       [ 0.09425992, -0.14570599, -0.98482731, -3.99988541],
       [ 0.03450864,  0.98911547, -0.14303753, -0.47155738],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [5]:
np.linalg.inv(M)

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [23]:
A=np.zeros_like(M)
A[:3,:3]=M[:3,:3].T
A[:3,-1]=np.matmul(-M[:3,:3].T, M[:3, -1])
A[3,3]=1
A

array([[ 0.99494936,  0.09425992,  0.03450864, -0.09820396],
       [-0.02050235, -0.14570599,  0.98911547, -0.10625439],
       [ 0.09826206, -0.98482731, -0.14303753, -4.05518832],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [24]:
np.abs(np.linalg.inv(M)-A)<1e-8

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
import torch
M=torch.randn(3,4,4)
M

tensor([[[-1.0515,  0.6854, -0.2414, -0.0772],
         [ 0.3678,  0.6213,  0.2522, -0.7743],
         [-0.7591, -0.5697, -0.1761, -0.3611],
         [-0.2778,  1.3940,  0.8210, -0.0120]],

        [[ 0.3847,  0.7167,  0.8006,  0.5021],
         [ 1.1498,  1.2870,  0.1477, -0.4163],
         [ 0.4068, -0.9256,  0.5818,  0.9137],
         [ 1.5051, -0.2232,  1.4569, -0.9175]],

        [[-0.3012, -0.6306,  1.1929,  0.7803],
         [ 0.9650, -0.2710,  0.4965, -2.1682],
         [ 0.4705,  1.6610,  0.2505,  0.4283],
         [-1.0500, -0.9464, -0.2267, -0.2603]]])

In [37]:
import numpy as np
idx=np.array([[0,1,2,0],[1,3,1,0],[0,3,2,0]])
M[idx]

tensor([ 0.3678, -0.9175,  0.4965, -1.0515])

In [39]:
M[[0,0,0,0,0,1,2,1,2,1]].shape

torch.Size([10, 4, 4])

In [16]:
M[torch.Tensor([0,1,4,5,6,7]).long(),:3,-1].shape

torch.Size([6, 3])

In [17]:
(torch.randn(10,4,5)@torch.randn(10,5,2)).shape

torch.Size([10, 4, 2])